### ISSUE TITLE
Only download button displayed

### ISSUE THREAD

**Issue by Wlad-K** [vaadin-component-factory/vcf-pdf-viewer-flow#15]
Hi, I use version 1.0.2 of pdf-viewer with Vaadin 14.8.4. I try to use it as follows, but only download button, which works, shows up:

```
PdfViewer pdfViewer = new PdfViewer();
pdfViewer.setSizeFull();
try {
    InputStream inputStream = new URL("https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf").openStream();
    StreamResource resource = new StreamResource("file.pdf", () -> inputStream);
    pdfViewer.setSrc(resource);

    getContent().add(pdfViewer);
} catch (IOException e) {
    e.printStackTrace();
}
```

I am adding it to VerticalLayout which has full width set. 
Any ideas? Am I doing something wrong?

Thank you

**Comment by Wlad-K** [comment]
Update: I switched to Vaadin 23.1.1 with pdf-viewer version 2.1.0. Issue still remains, only download button is displayed.

**Comment by paodb** [comment]
Hello @Wlad-K.  Is there any console error displaying?  I did a local test and everything seems to work okay. Here's my test project: [v23-pdf-viewer-test.zip](https://github.com/vaadin-component-factory/vcf-pdf-viewer-flow/files/9064157/v23-pdf-viewer-test.zip) Can you tell me if there's something else I'm missing there so I can reproduce your issue?

**Comment by Wlad-K** [comment]
Hello @paodb, your project is working. 
I turned log level to DEBUG, but unfortunately there is no log. Neither on backend nor browser console any error/warning is shown. Any idea how to investigate it more?

**Comment by paodb** [comment]
Hi @Wlad-K, what about browser console? any error there? Can you reproduce the issue in a simple project and share it with me so I can take a look?

**Comment by Wlad-K** [comment]
In the end what helped was to add pdf-viewer package in the `@EnableVaadin()` annotation in one of the modules we have.
