### ISSUE TITLE
Didn't work with Vaadin 24.4.x

### ISSUE THREAD

**Issue by dominik42** [vaadin-component-factory/vcf-pdf-viewer-flow#56]
Hi,

I migrate my Vaadin 24.3.x which contains

        <dependency>
            <groupId>org.vaadin.addons.componentfactory</groupId>
            <artifactId>vcf-pdf-viewer</artifactId>
            <version>3.0.0</version>
        </dependency>

to 24.4.8. After starting the application and on loading the first page in the browser, the following error occured and prevents the application from working any longer:

```
INFO c.v.b.devserver.DevServerOutputTracker   09:45:11 [vite] Failed to load source map for /Users/Dominik/Documents/dsd/steel42/frontend/generated/jar-resources/print-js/dist/print.js.
 INFO c.v.b.devserver.DevServerOutputTracker   Error: An error occurred while trying to read the map file at print.map
 INFO c.v.b.devserver.DevServerOutputTracker   Error: ENOENT: no such file or directory, open '/Users/Dominik/Documents/dsd/steel42/frontend/generated/jar-resources/print-js/dist/print.map'
 INFO c.v.b.devserver.DevServerOutputTracker       at async open (node:internal/fs/promises:637:25)
 INFO c.v.b.devserver.DevServerOutputTracker       at async Object.readFile (node:internal/fs/promises:1246:14)
 INFO c.v.b.devserver.DevServerOutputTracker       at async extractSourcemapFromFile (file:///Users/Dominik/Documents/dsd/steel42/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:20843:53)
 INFO c.v.b.devserver.DevServerOutputTracker       at async loadAndTransform (file:///Users/Dominik/Documents/dsd/steel42/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:52372:27)
```

I assume, the latest version of this pdf-viewer-addon is not compatibble with Vaadin 24.4.x .
Is there any plan for migration or exists any workaround to make the PdfViewer also working with the latest Vaadin version ?

Kind regards
Dominik

**Comment by allenvpn312** [comment]
The add-on works fine with the latest Vaadin version.  Try updating maven and re-built the front-end and hopefully that solves your problem.  Best.

**Comment by dominik42** [comment]
Indeed ... updating to version 3.0.0 and it works ... didn't know what I've done before ... thank you

**Comment by paodb** [comment]
Closing per comment https://github.com/vaadin-component-factory/vcf-pdf-viewer-flow/issues/56#issuecomment-2306533032
