### ISSUE TITLE
When zoomed in content is not displayed crisp at first

### ISSUE THREAD

**Issue by MatthiasK-creator** [vaadin-component-factory/vcf-pdf-viewer-flow#57]
When I zoom into a PDF, no matter the content, the content will not be displayed crisp, until I scroll vertically or horizontally, then it updates it's view and it will be crisp. See following video for an example:
https://github.com/user-attachments/assets/0127b21e-0185-4ffa-b03f-077dbcc5ae0e

Our Environment:

- Vaadin Flow Version 24.3.3
- vcf-pdf-viewer Version 3.0.0 (we previously had installed 2.8.1)

**Comment by paodb** [comment]
Reproducible also in Vaadin 24.4.10 with component version 3.0.0 & in Vaadin 23.5.2 with component version 2.7.4.
